export const namingDic : any = {
    "MMSE": "MMSE",
    "Verbal Comprehension Index": "WAIS5VCI",
    "Perceptual Reasoning Index": "WAIS5PRI",
    "Working Memory Index": "WAIS5WMI",
    "Processing Speed Index": "WAIS5PSI",
    "Full Scale IQ": "WAIS5FSIQ",
    "Similarities": "WAIS5SI",
    "Information": "WAIS5IN",
    "Block Design": "WAIS5BD",
    "Matrix Reasoning": "WAIS5MR",
    "Visual Puzzles": "WAIS5VP",
    "Digit Span": "WAIS5DS",
    "Arithmetic": "WAIS5AR",
    "Symbol Search": "WAIS5SS",
    "Vocabulary": "WAIS5VC",
    "Comprehension": "WAIS5CO",
    "Cancellation": "WAIS5CA",
    "Picture Completion": "WAIS5PCm",
    "Letter Numbering": "WAIS5LN",
    "Figure Weights": "WAIS5FW",
    "Coding": "WAIS5CD",
    "Test of Nonverbal Intelligence-4": "TONI4",
    "Trails A": "TrialsA",
    "Stroop Word (Golden)": "StroopWords",
    "Stroop Color (Golden)": "StroopColor",
    "Connors CPT3 Response Style": "CPT3RS",
    "Connors CPT3 d' *": "CPT3D",
    "Connors CPT3 Omissions *": "CPT3OM",
    "Connors CPT3 Commissions *": "CPT3CO",
    "Connors CPT3 Perseverations *": "CPT3PE",
    "Connors CPT3 HRT **": "CPT3HRT",
    "Connors CPT3 HRT SD *": "CPT3HRTS",
    "Connors CPT3 Variability *": "CPT3VI",
    "Connors CPT3 HRT Block Change*": "CPT3BC",
    "Connors CPT3 HRT ISI Change*": "CPT3ISICS",
    "Hooper Visual Organization Test": "Hooper",
    "Rey-O Copy": "ROCFCopy",
    "Boston Naming Test": "BNT",
    "FAS": "FAS",
    "Animal Naming": "Animals",
    "WMS-IV Logical Memory II": "WMS4LM2",
    "WMS-IV Logical Memory I": "WMS4LM1",
    "WMS-IV Log. Mem. Recog.": "WMS4LMRec",
    "RAVLT-trial 1": "RAVLTT1",
    "RAVLT-trial 2": "RAVLTT2",
    "RAVLT-trial 3": "RAVLTT3",
    "RAVLT-trial 4": "RAVLTT4",
    "RAVLT-trial 5": "RAVLTT5",
    "RAVLT-trials 1-5": "RAVLTT1to5",
    "RAVLT-list B": "RAVLTTB",
    "RAVLT-short delay recall": "RAVLTShortDelay",
    "RAVLT-long delay recall": "RAVLTLongDelay",
    "RAVLT-recognition": "RAVLTRec",
    "WMS-IV Visual Repro. II": "WMS4VR2",
    "WMS-IV Visual Repro. I": "WMS4VR1",
    "WMS-IV Vis. Rep. Recog.": "WMS4VRRec",
    "Rey-O-immediate": "ROCFIR",
    "Rey-O-delayed": "ROCFDR",
    "Rey-O-recognition": "ROCFRec",
    "WCST Categories Completed": "WCSTCC",
    "WCST Trials to 1st Category": "WCSTTC",
    "WCST Total Errors": "WCSTTE",
    "WCST Perseverative Errors": "WCSTPE",
    "WCST Nonperseverative Errors": "WCSTNE",
    "WCST % Conceptual Responses": "WCSTCR",
    "WCST Learning to Learn": "WCSTLL",
    "WCST Set Losses": "WCSTST",
    "Ruff Figural Fluency Total Designs": "RFFTSD",
    "Ruff Figural Fluency Error Ratio": "RFFTER",
    "Trails B": "TrialsB",
    "Stroop Color-Word (Golden)": "StroopColorWords",
    "The Dot Counting Test": "DCT",
    "B-Test": "BTest",
    "ACT (9\", 18\", 36\")":"ACT",
    "TOMM Trials 1, 2":"TOMM",
    "Booklet Category Test":"Booklet",
    "Short Category Test":"SCT"
}